name: Patch, Build and Release

on:
  push:
    branches: [ "**" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v3.6.0
        with:
          distribution: temurin
          java-version: 17
          cache: 'gradle'
      - name: Configure Git
        run: git config --global user.email "no-reply@github.com" && git config --global user.name "Github Actions"
      - name: Apply Patches
        run: ./gradlew applyPatches --no-daemon --stacktrace
      - name: Build Reobf Jar (Default)
        run: ./gradlew createReobfPaperclipJar --no-daemon --stacktrace
      - name: Rebuild on Failure
        if: ${{ failure() }}
        run: |
          ./gradlew clean cleanCache
          ./gradlew applyPatches --no-daemon --stacktrace
          ./gradlew createReobfPaperclipJar --no-daemon --stacktrace
          ./gradlew generateDevelopmentBundle --no-daemon --stacktrace
      - name: Set Commit Hash
        id: set_commit_hash
        run: echo "COMMIT_HASH=$(git log --format='%H' -n 1)" >> $GITHUB_ENV
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: Build ${{ github.run_number }}
          tag_name: ${{ github.run_number }}
          body: "Heres Downloads Ig?"
          token: ${{ secrets.TOKEN }}
          files: build/libs/*.jar